var searchData=
[
  ['handling_0',['Handling',['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/ci-integration-patterns.md#autotoc_md378',1,'4. Error Handling'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/advanced/multi-version-idf/index.md#autotoc_md63',1,'Error Handling']]],
  ['handling_20strong_1',['Handling strong',['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/configuration/index.md#autotoc_md580',1,'&lt;strong&gt;2. Validation and Error Handling&lt;/strong&gt;'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/build-system/index.md#autotoc_md356',1,'&lt;strong&gt;3. Error Handling&lt;/strong&gt;'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/flash-system/index.md#autotoc_md749',1,'&lt;strong&gt;3. Error Handling&lt;/strong&gt;'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/configuration/index.md#autotoc_md531',1,'&lt;strong&gt;Error Handling&lt;/strong&gt;']]],
  ['hardfoc_20esp_20idf_20ci_20tools_2',['Contributing to HardFOC ESP-IDF CI Tools',['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/contributing/index.md#autotoc_md586',1,'']]],
  ['hardfoc_20esp_20idf_20project_20tools_3',['HardFOC ESP IDF Project Tools',['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/README.md#autotoc_md994',1,'🔧 HardFOC ESP-IDF Project Tools'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/getting-started/index.md#autotoc_md776',1,'Getting Started with HardFOC ESP-IDF Project Tools'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/index.md#autotoc_md849',1,'HardFOC ESP-IDF Project Tools']]],
  ['hardware_20configuration_4',['🔌 Hardware Configuration',['../md_examples_2esp32_2README.html#autotoc_md22',1,'']]],
  ['hardware_20requirements_5',['🔧 Hardware Requirements',['../md_examples_2esp32_2README.html#autotoc_md2',1,'']]],
  ['help_6',['Help',['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/troubleshooting/index.md#autotoc_md986',1,'🆘 Getting Help'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/examples/index.md#autotoc_md655',1,'🆘 Need Help?'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/getting-started/index.md#autotoc_md788',1,'🆘 Need Help?'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/contributing/index.md#autotoc_md615',1,'📞 Getting Help'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/reference.md#autotoc_md962',1,'Getting Help'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/getting-started/project-setup/index.md#autotoc_md845',1,'Script Help'],['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/contributing/index.md#autotoc_md609',1,'Ways to Help']]],
  ['helper_20functions_20strong_7',['&lt;strong&gt;Helper Functions&lt;/strong&gt;',['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/configuration/index.md#autotoc_md561',1,'']]],
  ['host_8',['host',['../structEsp32As5047uBus_1_1SPIConfig.html#a2ad7553125bdda0294d7e94739826e5a',1,'Esp32As5047uBus::SPIConfig']]],
  ['how_20to_20contribute_9',['🤝 How to Contribute',['..//home/runner/work/hf-as5047u-driver/hf-as5047u-driver/examples/esp32/scripts/docs/contributing/index.md#autotoc_md587',1,'']]]
];
